#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" 

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lhAN --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" 

# These common commands are just too long! Abbreviate them.
alias \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" 

alias \
	magit="nvim -c MagitOnly" 
